[ { _id: 59e04f8f734d1d1c37fb77ce,
    location: 'Istanbul, Turkey',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: true,
    beer: true },
  { _id: 59e054da734d1d1c37fb7a37,
    location: 'Paris, France',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: true,
    wine: true,
    beer: false },
  { _id: 59e05505734d1d1c37fb7a49,
    location: 'Venice, Italy',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: true,
    beer: false },
  { _id: 59e0551d734d1d1c37fb7a4f,
    location: 'San Francisco, CA',
    cultural: true,
    outdoors: true,
    international: false,
    domestic: true,
    warm: true,
    cold: true,
    wine: true,
    beer: true },
  { _id: 59e05531734d1d1c37fb7a57,
    location: 'Barcelona, Spain',
    cultural: true,
    outdoors: true,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: true,
    beer: true },
  { _id: 59e0554b734d1d1c37fb7a5c,
    location: 'New York, New York',
    cultural: true,
    outdoors: false,
    international: false,
    domestic: true,
    warm: true,
    cold: true,
    wine: true,
    beer: true },
  { _id: 59e0556c734d1d1c37fb7a6f,
    location: 'Hong Kong, China',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: false,
    beer: true },
  { _id: 59e05585734d1d1c37fb7a76,
    location: 'Amsterdam, Netherlands',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: false,
    cold: true,
    wine: false,
    beer: true },
  { _id: 59e05cfe734d1d1c37fb7db3,
    location: 'Montreal, Canada',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: false,
    cold: true,
    wine: true,
    beer: true },
  { _id: 59e05d20734d1d1c37fb7e15,
    location: 'Bangkok, Thailand',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: false,
    beer: true },
  { _id: 59e05da2734d1d1c37fb7fc6,
    location: 'Prague, Czech Republic',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: false,
    cold: true,
    wine: true,
    beer: true },
  { _id: 59e05fd4734d1d1c37fb818e,
    location: 'Kauai, HI',
    cultural: false,
    outdoors: true,
    international: false,
    domestic: true,
    warm: true,
    cold: false,
    wine: false,
    beer: true },
  { _id: 59e05fef734d1d1c37fb8192,
    location: 'Tuscany, Italy',
    cultural: true,
    outdoors: true,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: true,
    beer: false },
  { _id: 59e06010734d1d1c37fb8198,
    location: 'Aspen, CO',
    cultural: false,
    outdoors: true,
    international: false,
    domestic: true,
    warm: false,
    cold: true,
    wine: false,
    beer: true },
  { _id: 59e0602a734d1d1c37fb81a0,
    location: 'Santorini, Greece',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: true,
    beer: true },
  { _id: 59e06045734d1d1c37fb81ad,
    location: 'Tulum, Mexico',
    cultural: true,
    outdoors: true,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: false,
    beer: true },
  { _id: 59e06062734d1d1c37fb81be,
    location: 'Bali, Indonesia',
    cultural: false,
    outdoors: true,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: false,
    beer: true },
  { _id: 59e0608f734d1d1c37fb81dd,
    location: 'Port Douglas, Australia',
    cultural: false,
    outdoors: true,
    international: true,
    domestic: false,
    warm: true,
    cold: false,
    wine: false,
    beer: true },
  { _id: 59e060a7734d1d1c37fb81e6,
    location: 'Finger Lakes, NY',
    cultural: false,
    outdoors: true,
    international: false,
    domestic: true,
    warm: false,
    cold: true,
    wine: true,
    beer: false },
  { _id: 59e060c6734d1d1c37fb81f3,
    location: 'Bavaria, Germany',
    cultural: true,
    outdoors: true,
    international: true,
    domestic: false,
    warm: true,
    cold: true,
    wine: true,
    beer: false },
  { _id: 59e060e4734d1d1c37fb8202,
    location: 'Dublin, Ireland',
    cultural: true,
    outdoors: true,
    international: true,
    domestic: false,
    warm: false,
    cold: true,
    wine: false,
    beer: true },
  { _id: 59e25dad734d1d1c37fc848c,
    location: 'Seoul, South Korea',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: true,
    wine: false,
    beer: true },
  { _id: 59e25efb734d1d1c37fc84ce,
    location: 'Banff, Canada',
    cultural: false,
    outdoors: true,
    international: true,
    domestic: false,
    warm: true,
    cold: true,
    wine: true,
    beer: true },
  { _id: 59e25f5b734d1d1c37fc84e7,
    location: 'Tokyo, Japan',
    cultural: true,
    outdoors: false,
    international: true,
    domestic: false,
    warm: true,
    cold: true,
    wine: false,
    beer: true } ]